### ISSUE TITLE
java.io.FileNotFoundException when @import name ends in `*less`

### ISSUE THREAD

**Issue by esamson** [marceloverdijk/lesscss-java#4]
I have a file named `frameless.less`, but when I do

```
@import "frameless";
```

I get

```
java.io.FileNotFoundException: File /Users/esamson/ ... /frameless not found.
     at org.lesscss.LessSource.<init>(LessSource.java:59)
     at org.lesscss.LessSource.resolveImports(LessSource.java:145)
     at org.lesscss.LessSource.<init>(LessSource.java:63)
    ...
```

Workaround is to say

```
@import "frameless.less";
```

But it would be nicer to be able to omit the `.less` extension, which works fine when just using _less.js_.

**Comment by candrews** [comment]
I merged your pull request - thanks!
