### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by alexkalderimis** [marceloverdijk/lesscss-java#55]
I can reproduce the error below when I deploy to heroku (but not on my own machine). I would really appreciate any input on this, as I am not at all sure how to resolve this issue. It seems to be related to the optimisation, so I wonder if a suitable solution would be to make the optimisation level parameterisable?

```
java.lang.IllegalAccessError: tried to access method org.mozilla.classfile.ClassFileWriter.getLabelPC(I)I from class org.mozilla.javascript.optimizer.BodyCodegen$ExceptionManager
        at org.mozilla.javascript.optimizer.BodyCodegen$ExceptionManager.endCatch(Codegen.java:4051)
        at org.mozilla.javascript.optimizer.BodyCodegen$ExceptionManager.removeHandler(Codegen.java:3952)
        at org.mozilla.javascript.optimizer.BodyCodegen.visitTryCatchFinally(Codegen.java:3705)
        at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1897)
        at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1873)
        at org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1858)
        at org.mozilla.javascript.optimizer.BodyCodegen.generateBodyCode(Codegen.java:1289)
        at org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:306)
        at org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:166)
        at org.mozilla.javascript.optimizer.Codegen.compile(Codegen.java:75)
        at org.mozilla.javascript.Context.compileImpl(Context.java:2377)
        at org.mozilla.javascript.Context.compileReader(Context.java:1296)
        at org.lesscss.LessCompiler.init(LessCompiler.java:289)
        at org.lesscss.LessCompiler.compile(LessCompiler.java:351)
        at org.lesscss.LessCompiler.compile(LessCompiler.java:444)
```

**Comment by alexkalderimis** [comment]
just fyi: I don' think this has anything to do with your project, but with the Heroku environment. You can follow my attempts to resolve it here: http://stackoverflow.com/questions/24429578/how-can-i-resolve-this-illegalaccesserror-in-org-mozilla-javascript-optimizer-bo
