### ISSUE TITLE
Exception on every LESS code

### ISSUE THREAD

**Issue by enexusde** [marceloverdijk/lesscss-java#73]
Using tomcat 8.0.32 this is my code:

>		try {
>			return lessCompiler.compile("");
>		} catch (LessException e) {
>			byte[] bytes = lesscss.getBytes();
>			LOG.log(Level.WARNING, "Could not compile less: '" + lesscss + "' (bytes: " + Arrays.toString(bytes) + ")",
>					e);
>			throw e;
>		}

I got this exception on an empty string (""):

> 04-May-2018 18:40:36.549 WARNING [ajp-nio-8009-exec-8] com.sotacms.server.cms.extra.service.LessCssTemplateProcessor.generateCSS Could not compile less: '' (bytes: [])
 org.lesscss.LessException: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
        at org.lesscss.LessCompiler.compile(LessCompiler.java:426)
        at org.lesscss.LessCompiler.compile(LessCompiler.java:330)
        at org.lesscss.LessCompiler.compile(LessCompiler.java:312)
        at com.sotacms.server.cms.extra.service.LessCssTemplateProcessor.generateCSS(LessCssTemplateProcessor.java:38)
        at com.sotacms.server.cms.extra.share.template.TemplateShareController.upload(TemplateShareController.java:147)
        at com.sotacms.server.cms.extra.share.template.TemplateShareController$$FastClassBySpringCGLIB$$249cd8f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
        at com.sotacms.server.cms.extra.share.template.TemplateShareController$$EnhancerBySpringCGLIB$$e117e0a3.upload(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:775)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:867)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:841)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:868)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
        at java.lang.String.charAt(String.java:658)
        at org.apache.catalina.loader.WebappClassLoaderBase.filter(WebappClassLoaderBase.java:2780)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1253)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
        at org.mozilla.javascript.Kit.classOrNull(Kit.java:60)
        at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:127)
        at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:82)
        at org.mozilla.javascript.NativeJavaTopPackage.init(NativeJavaTopPackage.java:96)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.mozilla.javascript.ScriptableObject.buildClassCtor(ScriptableObject.java:1225)
        at org.mozilla.javascript.LazilyLoadedCtor.buildValue0(LazilyLoadedCtor.java:105)
        at org.mozilla.javascript.LazilyLoadedCtor.access$000(LazilyLoadedCtor.java:18)
        at org.mozilla.javascript.LazilyLoadedCtor$1.run(LazilyLoadedCtor.java:90)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.mozilla.javascript.LazilyLoadedCtor.buildValue(LazilyLoadedCtor.java:86)
        at org.mozilla.javascript.LazilyLoadedCtor.init(LazilyLoadedCtor.java:66)
        at org.mozilla.javascript.ScriptableObject$GetterSlot.getValue(ScriptableObject.java:307)
        at org.mozilla.javascript.ScriptableObject.get(ScriptableObject.java:456)
        at org.mozilla.javascript.IdScriptableObject.get(IdScriptableObject.java:329)
        at org.mozilla.javascript.ImporterTopLevel.get(ImporterTopLevel.java:96)
        at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2184)
        at org.mozilla.javascript.ScriptRuntime.topScopeName(ScriptRuntime.java:1824)
        at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1791)
        at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1733)
        at org.mozilla.javascript.gen.jar_file__usr_local_share_apache_tomcat_8_0_32_sotacms_ROOT_WEB_INF_lib_lesscss_1_7_0_1_1_jar__META_INF_less_rhino_1_7_0_js_1._c_anonymous_3(jar:file:/usr/local/share/apache-tomcat-8.0.32/sotacms/ROOT/WEB-INF/lib/lesscss-1.7.0.1.1.jar!/META-INF/less-rhino-1.7.0.js:24)
        at org.mozilla.javascript.gen.jar_file__usr_local_share_apache_tomcat_8_0_32_sotacms_ROOT_WEB_INF_lib_lesscss_1_7_0_1_1_jar__META_INF_less_rhino_1_7_0_js_1.call(jar:file:/usr/local/share/apache-tomcat-8.0.32/sotacms/ROOT/WEB-INF/lib/lesscss-1.7.0.1.1.jar!/META-INF/less-rhino-1.7.0.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
        at org.mozilla.javascript.gen.jar_file__usr_local_share_apache_tomcat_8_0_32_sotacms_ROOT_WEB_INF_lib_lesscss_1_7_0_1_1_jar__META_INF_less_rhino_1_7_0_js_1._c_anonymous_2(jar:file:/usr/local/share/apache-tomcat-8.0.32/sotacms/ROOT/WEB-INF/lib/lesscss-1.7.0.1.1.jar!/META-INF/less-rhino-1.7.0.js:23)
        at org.mozilla.javascript.gen.jar_file__usr_local_share_apache_tomcat_8_0_32_sotacms_ROOT_WEB_INF_lib_lesscss_1_7_0_1_1_jar__META_INF_less_rhino_1_7_0_js_1.call(jar:file:/usr/local/share/apache-tomcat-8.0.32/sotacms/ROOT/WEB-INF/lib/lesscss-1.7.0.1.1.jar!/META-INF/less-rhino-1.7.0.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
        at org.mozilla.javascript.gen.jar_file__usr_local_share_apache_tomcat_8_0_32_sotacms_ROOT_WEB_INF_lib_lesscss_1_7_0_1_1_jar__META_INF_less_rhino_1_7_0_js_1._c_script_0(jar:file:/usr/local/share/apache-tomcat-8.0.32/sotacms/ROOT/WEB-INF/lib/lesscss-1.7.0.1.1.jar!/META-INF/less-rhino-1.7.0.js:21)
        at org.mozilla.javascript.gen.jar_file__usr_local_share_apache_tomcat_8_0_32_sotacms_ROOT_WEB_INF_lib_lesscss_1_7_0_1_1_jar__META_INF_less_rhino_1_7_0_js_1.call(jar:file:/usr/local/share/apache-tomcat-8.0.32/sotacms/ROOT/WEB-INF/lib/lesscss-1.7.0.1.1.jar!/META-INF/less-rhino-1.7.0.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at org.mozilla.javascript.gen.jar_file__usr_local_share_apache_tomcat_8_0_32_sotacms_ROOT_WEB_INF_lib_lesscss_1_7_0_1_1_jar__META_INF_less_rhino_1_7_0_js_1.call(jar:file:/usr/local/share/apache-tomcat-8.0.32/sotacms/ROOT/WEB-INF/lib/lesscss-1.7.0.1.1.jar!/META-INF/less-rhino-1.7.0.js)
        at org.lesscss.LessCompiler.compile(LessCompiler.java:383)
        ... 51 more

No matter what code I insert, always the SAME exception.

**Comment by enexusde** [comment]
This is not a lesscss problem. Upgrade from Tomcat 8.0.32 to a later version of Tomcat solved this problem.
